spring.application.name=sudab

#Nombre de la base de datos, usuario y contraseña
spring.datasource.url=jdbc:postgresql://ep-divine-bonus-acdcecau-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_b2rmGo7zMJYB
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=mysecretkey

spring.config.import=optional:file:.env[.properties]

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


server.port=8080
server.servlet.context-path=/api/v1