spring.application.name=sudab

# variables de entorno 
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Clave JWT
jwt.secret=${TOKEN_JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:120000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# Puerto dinámico:
server.port=${PORT:8080}


spring.config.import=optional:file:.env[.properties]

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect